### ISSUE TITLE
Fails to build with transformers-0.6.1

### ISSUE THREAD

**Issue by nikita-volkov** [snowleopard/selective#69]
```
src/Control/Selective/Trans/Except.hs:51:7: error:
    • Could not deduce (Selective m)
        arising from the 'deriving' clause of a data type declaration
      from the context: Monad m
        bound by a quantified context
        at src/Control/Selective/Trans/Except.hs:51:7-16
      Possible fix:
        add (Selective m) to the context of a quantified context
        or use a standalone 'deriving instance' declaration,
             so you can specify the instance context yourself
    • When deriving the instance for (MonadTrans (ExceptT e))
   |
51 |     , MonadTrans, MonadFix, MonadFail, MonadZip, MonadIO, MonadPlus, Eq1, Ord1
   |       ^^^^^^^^^^
```

**Comment by snowleopard** [comment]
Thanks! I fixed it by dropping the `MonadTrans` instance, with the following justification:

https://github.com/snowleopard/selective/blob/35be65c2de183bdbe6735e68b2045f20acf3d932/src/Control/Selective/Trans/Except.hs#L53-L87

I'll release a new version soon.

**Comment by nikita-volkov** [comment]
Oh damn it's gonna be another major release. I've only just updated my deps 😅

**Comment by nikita-volkov** [comment]
This shouldn't make you hesitate to make the release though :)

**Comment by snowleopard** [comment]
Done: https://hackage.haskell.org/package/selective-0.6.1 :)

**Comment by snowleopard** [comment]
Oh, shoot, should it have been `0.7` since it's a breaking change?

**Comment by snowleopard** [comment]
(I contacted Hackage Trustees.)

**Comment by snowleopard** [comment]
This makes me think... shouldn't `transformers-0.6.1` be `transformers-0.7` too?

**Comment by snowleopard** [comment]
Anyway, replaced with https://hackage.haskell.org/package/selective-0.7
